config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:new]
  resource :session, only: [:create, :destroy]
  get 'boards/global' => 'boards#global', as: :global
  resources :boards
  resources :photos

  get 'about' => 'welcome#about', as: :about
  get 'main' => 'welcome#index', as: :main
  

  root 'welcome#index'
  

end

app/models/board.rb
class Board
  include Mongoid::Document
 
  
  field :name, type: String
  field :type, type: String
  field :description, type: String
  
  belongs_to :user
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Paperclip


  belongs_to :user
  has_mongoid_attached_file :image
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :is_admin, type: Boolean, :default => false

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates_uniqueness_of :email
  

  has_secure_password
  has_many :boards, dependent: :destroy
  # dependent: :destroy destroys all boards associated
  # with each user if a user is destroyed.
 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :login, :signup

  def index
    if current_user && current_user.is_admin
      @boards = Board.all
    else
      redirect_to new_session_path
    end
    @photo = Photo.new
  end

  def global
    @photos = Photo.all
  end


  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    if !current_user 
      alert("You must be signed-in for this feature")
      redirect_to new_session_path
    else
      @board = current_user.boards.new(params.require(:board).permit(:name, :type, :description))
      if @board.save
        redirect_to user_path(current_user)
      else 
        render 'new'
      end 
    end
    
  end

  def edit
    if current_user # && current_user.id == User.find(params[:id]).id
      @board = Board.find(params[:id])
  
    else
      redirect_to root_path
    end
  end

  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(params.require(:board).permit(:name, :type, :description))
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    # if current_user
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to user_path(current_user)
    # else
      # @board = Board.find(params[:id])
      # @board.destroy
      # redirect_to boards_path
    end
  end 

# function added to for admin to delete boards.
  # def admin_delete
  #   @admin_board = Board.find(params[:id])
  #   @admin_board.destroy
  # end

  def login
    @user_login = User.new
    @is_login = true
  end
  
  def signup
    @user_signup = User.new
  end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :login, :signup
  def index
    @photos = Photo.all
  end

  def new
    if current_user && current_user.is_admin
      @photo = Photo.new
    else
      redirect_to global_path
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

 def create
  if current_user.is_admin
    @photo = Photo.new(photo_params)
  end
  if @photo.save
    redirect_to global_path
  else
    render 'new'
  end
 end

def login
    @user_login = User.new
    @is_login = true
  end

  def signup
    @user_signup = User.new
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy 
    redirect_to global_path
  end


private

  def photo_params
    params.require(:photo).permit(:image)
  end

end

#   def new
#     @photo =Photo.new
#   end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 

  def create
    user = User.where(email: params[:user][:email]).first
    # Checks to see if the user exists, and then for a matching password
    if user && user.authenticate(params[:user][:password])
      # Creates a cookie for the user, holding the logged in user ID
      session[:user_id] = user.id.to_s
      if current_user.is_admin
        redirect_to boards_path
      else
        redirect_to user_path(current_user)
      end
    else
      flash[:error] = "Email or Password do not match! Please try again"
      redirect_to main_path

    end
  end

  def destroy
    # Kill all of our cookies
    reset_session
    redirect_to main_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :login, :signup


  def index
    if current_user 

    else
      redirect_to new_user_path
    end
  end

  

  def show
    @user = User.find(params[:id])
    @boards = current_user.boards.all
    @board = current_user.boards.new
  end


  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path(@user)
    else
      redirect_to main_path
    end
  end

  def edit
    if current_user && current_user.id == User.find(params[:id]).id
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:name, :email, :password, :password_confirmation))
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    reset_session
    User.find(params[:id]).destroy
    redirect_to main_path
  end

   def login
    @user_login = User.new
    @is_login = true
  end

  def signup
    @user_signup = User.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :login, :signup
  def index
  end

  def about
  end

  def login
    @user_login = User.new
    @is_login = true
  end

  def signup
    @user_signup = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<h1>EDIT THIS BOARD</h1>


<%= form_for @board do |f| %>
    <%= f.text_field :name, placeholder: 'Name' %>
    <%= f.text_field :type, placeholder: 'Type' %>
    <%= f.text_field :description, placeholder: 'Description' %>
    <%= f.submit 'Save Changes' %>
    <%= link_to 'Delete Board', @board, method: :delete %>

  <% end %>

app/views/boards/global.html.erb
<!-- 
<div class="galleryContainer">
<div class="text-center">
  <h2>Gallery</h2>
</div>

<div class = "galleryContent">
  <%# @photos.each do |p| %>
  <%#= image_tag p.image, size: "250x200" %>
</div>


<%# if current_user && current_user.is_admin %>
  <%#= link_to 'Delete', p,method: :delete, data: {confirm:'Are you sure?'} %>
<%# end %>

<%# end %>

</div> -->



<body>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Gallery</h1>
            </div>

            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("1.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("2.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("3.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("4.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("5.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("6.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("7.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("8.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("9.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("10.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("11.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("12.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("13.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("14.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("15.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("16.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("17.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("18.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("19.JPG", :alt => "") %>
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag("20.JPG", :alt => "") %>
                </a>
            </div>
        </div>

        <hr>

        <!-- Footer -->
    

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    <script src="js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

app/views/boards/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<link href='http://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>

<div class="admin-board">

<h3> Board Requests </h3>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th>Contacted</th>
      <th>Finished</th>
      <!-- <th>Delete</th> -->
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |b| %>
    <tr class="table-odd">
      <td><%= b.name %></td>
      <td><%= b.type %></td>
      <td><%= b.description %></td>
      <td><input type="checkbox"><br><input type="text" placeholder="Date"></td>
      <td><input type="checkbox"><br><input type="text" placeholder="Date"></td>
      <!-- <td><%#= link_to 'Delete Board', @admin_board, method: :delete %></td> -->
    <% end %>
    </tr>
  </tbody>
</table>
<br>

<div class="upload">
<h3>Uploading Images</h3>

<% if current_user && current_user.is_admin %>
  <%= form_for @photo, {url: photos_path(@photo)} do |f| %> 

  <%= f.file_field :image %> <br> <%= f.submit "Upload" %>
  <% end %>

<% end %>
<p> Images will automically be shown in gallery</p>
</div>


</div>

app/views/boards/new.html.erb
<h1> Not using 8-15-14 </h1>

<p> Images of boards </p>

<p> Sign up to make a custom board of your own! </p>

<%#= link_to "SHOW", user_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Homemade+Apple' rel='stylesheet' type='text/css'>

 
</head>
<body>
  <%= render 'partials/modal' %>
  <%= render 'partials/nav' %>


<%= yield %>









</body>
</html>

app/views/partials/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <div class= "form-group">
        <%= form_for @user_login, {url: session_path} do |f| %>
        <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %><br>
        <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %><br>
          <br>
      
  
        </div>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Login', class: 'btn btn-success' %>
        <% end %>

      
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="signup_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign-up</h4>
      </div>
      <div class="modal-body">
        <div class= "form-group">
           <%= form_for @user_signup do |f| %>
    <%= f.text_field :name, placeholder: 'Name',class: 'form-control' %><br>
    <%= f.text_field :email, placeholder: 'Email',class: 'form-control' %><br>
    <%= f.password_field :password, placeholder: 'Password',class: 'form-control' %><br>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm Password',class: 'form-control' %>
        </div>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Sign up', class: 'btn btn-success' %>
        <% end %>
        
      
      </div>
    </div>
  </div>
</div>



   

    

app/views/partials/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'markiboards copy-01.bmp', class: "navbar-brand" %>    Boards</a>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Gallery", global_path %></li>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/main">About the Company</a></li>
            <li><a href="/about">About Marc Takaki</a></li>      
          </ul>
        </li>
       </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <p class="navbar-text">Hello, <%= current_user.name %></p>
        <% end %>

        <li>
          <% if current_user && current_user.is_admin %>
          <%= link_to 'Admin Only', boards_path %>
          <% else %>
          
          <% end %>
        </li>
        <li>
          <% if current_user %>
          <%= link_to 'Your Account', user_path(current_user.id) %>
          <% else %>
          <% end %>
        </li>
        <li>
          <% if current_user %>
          <%= link_to 'Edit Profile', edit_user_path(current_user.id) %>
          <% else %>
           <a href="#" data-toggle="modal" data-target="#signup_modal">Sign up</a>
           <% end %>
        </li>
        <li>
          <% if current_user %>
          <%= link_to 'Logout', session_path, method: :delete %>
          <% else %>
          <!-- Button trigger modal -->
        
            <a href="#" data-toggle="modal" data-target="#myModal" >Log in</a>
          <% end %>
        </li>









  
       

      </ul>
    </div><!-- /.navbar-collapse --
  </div><!-- /.container-fluid -->
</nav>

app/views/photos/new.html.erb
<h1>something</h1>

<% if current_user && current_user.is_admin %>
  <%= form_for @photo, {url: photos_path(@photo)} do |f| %> 
  <%= f.file_field :image %> <%= f.submit "Upload" %>
  <% end %>
  <%= link_to 'Admin Only', boards_path %>
<% end %>

app/views/users/edit.html.erb
<link href='http://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>


<div class="edit-profile">
<h1>Edit Profile</h1>
    <%= form_for @user do |f| %>
    <%= f.text_field :name, placeholder: 'Name' %>
    <%= f.text_field :email, placeholder: 'Email' %>
    <%= f.password_field :password, placeholder: 'Password' %>
    <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %>
    <%= f.submit 'Save Changes' %>
    <% end %>
<br>
    <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: "Permanently delete this account?" } %>
</div>
    

app/views/users/index.html.erb
<h1> Marki boards </h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

app/views/users/show.html.erb
<link href='http://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>

<div class="custom-board">
<h3><strong> Make a custom board </strong></h3>
<br>
<br>
<div class="inner-container">
<p> Step 1: The Basics</p>
<%= form_for @board do |f| %>
Name: <%= f.text_field :name, placeholder: "Name" %>
<br>
<br>
<br>

<p> Step 2: Choose your board</p>

Type: <%= f.text_field :type, placeholder: "Type" %>

<%= image_tag("Hand_boards.jpg", :alt => "") %>
<p> Funboards / High Performances Shortboards / Fishes
<br>
<br>
<p> Step 3: Design your board </p>
<%= f.text_field :description, placeholder: "Description" %>


<br>
<br>
<br>
<p> Step 4: Double check and lets make a board!</p>
<%= f.submit "submit!" %>

<% end %>
</div>

<br>
<br>
<br>
<br>
<h3> Board Orders </h3>
<% @boards.each do |b| %>
<br>
<li>
  <%= b.name %> <%= b.type %> <%= b.description %>
  <br>
  <%= link_to 'Edit your orders', edit_board_path(b.id) %>
</li> 
<% end %>
</div>
<br>


<br>
<br>


 

app/views/welcome/about.html.erb
 <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
  <hr>
        <div class="text-center center-block">
              <a href="https://www.facebook.com/Marki.boards" target="_blank>"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a>
             <!--  <a href="https://twitter.com/bootsnipp"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a> -->
              <a href="mailto:mark.boards@gmail.com"><i id="social" class="fa fa-envelope-square fa-3x social-em"></i></a>
              <a href="http://instagram.com/marki_boards" target="_blank>"><i id="social" class="fa fa-camera-retro fa-3x social-in"></i></a>
        </div>
  <hr>
</div>

<br />





<div id="wrapper">

<div class="contains">
<div class="inside" id= "marcphoto">
  
</div>



<div class="inside" id="text-left">
<h3><strong>Marc Takaki</strong></h3>
<br>
<p class="first">
   I was born on July 29, 1988 and live in Southern California. I enjoy outdoor extreme sports and hanging out with friends. I began skateboarding and surfing around middle school, and was instantly hooked. I spent most of my time hanging out at the beach or skatepark with friends. Eventually I leaned more towards surfing because I loved how relaxing and challenging it is. </p>
  <br>
<p class="second">
  My father (who was an avid surfer) taught me how to use hand and power tools on basic household repairs starting at a young age. I took that knowledge and began making cruiser skateboard decks and applying custom grip tape designs for myself. I found from making those skateboards that I enjoy crafting things with my hands and seeing them actually work. From then on if I could make something instead of buying it I had to try.</p> 
  <br>
  <p class="third">
  I try to be as creative as possible and like to put my own flair on the boards, while at the same time keeping them functional and able to perform well. I am also a perfectionist and I do not like to give others boards that I am not one hundred percent satisfied with. I love working with others to craft exactly what they want. My goal is to make the customer happy and  to put a good surfboard under their feet. Having a board custom for your body and ability makes surfing a lot more fun!</p>
  <br>  
<p class="fourth">
  With that being said, I would like to say thank you for showing interest in my boards and for all your support! I hope to work with all of you and make new friends along the way!
  <br>
  <br>

</p>
</div>
</div>
</div>

app/views/welcome/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Ubuntu:500' rel='stylesheet' type='text/css'>

<div class="text-center">
  

<div class="carousel-wrapper">
<div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
    <li data-target="#carousel-example-generic" data-slide-to="5"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active item-1">
      <%= image_tag("_MG_6900.JPG", :alt => "") %>
      <div class="carousel-caption"></div>
    </div>

    <div class="item item-2">
      <%= image_tag("_MG_6873.JPG", :alt => "") %>
      <div class="carousel-caption"></div>
    </div>


  <div class="item item-3">
      <%= image_tag("_MG_6870.JPG", :alt => "") %>
      <div class="carousel-caption"></div>
    </div>


  <div class="item item-4">
      <%= image_tag("_MG_6866.JPG", :alt => "") %>
      <div class="carousel-caption"></div>
    </div>

  <div class="item item-5">
      <%= image_tag("_MG_6870.JPG", :alt => "") %>
      <div class="carousel-caption"></div>
    </div>

  <div class="item item-6">
      <%= image_tag("_MG_6873.JPG", :alt => "") %>
      <div class="carousel-caption"></div>
    </div>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

</div>
</div>

    <br>


<br />

<div class="container">
    <div class="text-left">
      <h4 id="About"><strong>About The Company</strong></h4>
      <p>Marki was established in 2013 and is based in Southern California. The name is a combination between my first and last name.  It has also been a nickname of mine when I was younger, that almost all of my family used to call me. All of the boards are shaped and glassed by me. Marki focuses on making custom and unique boards to the riders request. I like to work new and repeated customers to dial in as close to a perfect board as possible for them.  
    <br>
    <br>
      I began making hand planes for bodysurfing. I made a couple for myself and then decided to see if I can make some that others would like to enjoy. Surprising to me a lot of people showed interest in my craftsmanship and began buying them off of me. After making a bunch of plain ones i began experimenting with stringers and wood pattern inlays and it helped me understand a lot about woodworking, while at the same time making the boards look unique and artistic without having to use stains or paint. 
    <br>
    <br>
      After a year and a half of making hand planes, I noticed that surfboard shaping uses the exact same tools as a woodworker uses. I watched a lot of videos and went to conventions where shapers shaped in front of an audience. After watching and asking a lot of questions I decided to give it a shot. I shaped my first board not knowing what to expect. It took me a while but i got it. I then made the decision to learn how to glass it as well. After it was completed I took it to the water and was surprised at how well it worked! Though it had a lot of problems, I was determined to make another that was better and fix errors that I had made. I shaped a few more for myself, and then friends began to ask me for one. Suddenly people who i have not even met began asking me for a board. From all of that practice, I have shaped many boards and with each one I learn something new.    
    <br>
    <br>
      I strive to make each board unique that will fit the riders specifications and style by various shapes and materials.  Hopefully in the future I can continue to grow and learn. I only want to get better and am looking forward to working and meeting with as many people as possible! </p>
    </div>
</div>
 <br>
 <br>
 
  

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
  <hr>
        <div class="text-center center-block">
              <a href="https://www.facebook.com/Marki.boards" target="_blank>"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a>
             <!--  <a href="https://twitter.com/bootsnipp"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a> -->
              <a href="mailto:mark.boards@gmail.com"><i id="social" class="fa fa-envelope-square fa-3x social-em"></i></a>
              <a href="http://instagram.com/marki_boards" target="_blank>"><i id="social" class="fa fa-camera-retro fa-3x social-in"></i></a>
        </div>
  <hr>
</div>

    <script>

    

    $('html, body').animate({
        scrollTop: $('#About').offset().top
    }, 950);

    

    </script>
    